export type Permission =
  | 'activity:read'
  | 'activity:create'
  | 'activity:edit'
  | 'activity:delete'
  | 'activity:publish'
  | 'registration:create'
  | 'registration:read'
  | 'registration:delete'
  | 'attendance:validate'
  | 'user:manage'